name: CI with Unit Tests and SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install cmake g++ gcovr -y

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DENABLE_TESTING=ON -DCODE_COVERAGE=ON

      - name: Build Project
        run: |
          cd build
          cmake --build .

      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate Coverage Report
        run: |
          cd build
          make coverage

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.login=$SONAR_TOKEN
